-- =====================================================================
-- Smart Agri Surveillance - Supabase schema (migration 0001)
-- ---------------------------------------------------------------------
-- This is a faithful port of the original SQLAlchemy/SQLite models that
-- lived in `backend/app/models/*.py`. Every table and every column the
-- existing application already used is preserved with the SAME name and
-- the SAME semantics, so all existing API routes, the dashboard, the
-- detection logs, analytics and camera management keep working unchanged.
--
-- Changes vs. the SQLite schema:
--   1. users.id is now a uuid that references auth.users (Supabase Auth
--      owns credentials; we no longer store a local password hash).
--   2. Camera passwords moved out of `cameras` into `camera_secrets`,
--      which has no RLS policies at all - so a camera credential can
--      never be read with the browser's anon key. The `cameras` table
--      keeps `username` (the old API already returned it) but never the
--      password.
--   3. detections gains `bounding_box` + `metadata` (jsonb) and an
--      idempotency key `client_event_id` used by the local AI server's
--      offline outbox so replayed events can never duplicate.
--   4. alerts gains `alert_type` plus a STORED generated `status`
--      column, which keeps the spec's `status` field always consistent
--      with the existing acknowledged/resolved booleans.
-- =====================================================================

-- ---------------------------------------------------------------------
-- users  (application profile mirroring the Supabase Auth user)
-- ---------------------------------------------------------------------
create table if not exists public.users (
    id          uuid primary key references auth.users (id) on delete cascade,
    email       text,
    username    text unique,
    name        text,
    role        text        not null default 'user',
    is_active   boolean     not null default true,
    created_at  timestamptz not null default now(),
    last_seen_at timestamptz
);

comment on table public.users is
    'Application user profile. Authentication itself lives in Supabase Auth (auth.users); this table only carries app data (role, display name).';

create index if not exists ix_users_username on public.users (username);
create index if not exists ix_users_role    on public.users (role);

-- ---------------------------------------------------------------------
-- cameras
-- ---------------------------------------------------------------------
create table if not exists public.cameras (
    id              bigint generated by default as identity primary key,
    camera_code     text        not null unique,          -- e.g. CAM-001
    name            text        not null,
    location        text,
    description     text,
    zone            text,

    camera_type     text        not null default 'Local Webcam',
    connection_type text        not null default 'local_webcam', -- local_webcam | ip_camera | rtsp | http_mjpeg
    device_index    integer,                            -- for local_webcam
    stream_url      text,                                -- for network cameras (never contains credentials)
    username        text,                                -- preserved: the previous API already returned this

    enabled         boolean     not null default true,

    -- Runtime health, written by the local AI server only.
    status           text    not null default 'unknown',  -- unknown | testing | online | offline
    last_fps         double precision,
    last_latency_ms  double precision,
    last_seen_at     timestamptz,
    last_error       text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint cameras_connection_type_check
        check (connection_type in ('local_webcam', 'ip_camera', 'rtsp', 'http_mjpeg'))
);

create index if not exists ix_cameras_camera_code on public.cameras (camera_code);
create index if not exists ix_cameras_enabled     on public.cameras (enabled);

-- ---------------------------------------------------------------------
-- camera_secrets  (service-role only - NO RLS policies are created)
-- ---------------------------------------------------------------------
create table if not exists public.camera_secrets (
    camera_id  bigint primary key references public.cameras (id) on delete cascade,
    -- Same scheme as the original app: 'env:VAR_NAME' (recommended) or
    -- 'obf:<xor-base64>' (obfuscated with a local key file).
    password   text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

comment on table public.camera_secrets is
    'Camera passwords. Deliberately has no RLS policies, so it is unreachable with the anon/authenticated keys and can only be read or written with the service-role key by the local AI server.';

-- ---------------------------------------------------------------------
-- video_analysis_jobs
-- ---------------------------------------------------------------------
create table if not exists public.video_analysis_jobs (
    id                bigint generated by default as identity primary key,
    original_filename text        not null,
    status            text        not null default 'queued', -- queued | processing | completed | failed | cancelled
    total_frames      integer,
    processed_frames  integer     not null default 0,
    progress_percent  double precision not null default 0,
    source_fps        double precision,
    event_count       integer     not null default 0,
    error_message     text,
    cancel_requested  boolean     not null default false,
    created_at        timestamptz not null default now(),
    started_at        timestamptz,
    completed_at      timestamptz,
    client_job_id     uuid unique          -- idempotency key for offline replay
);

create index if not exists ix_video_jobs_created on public.video_analysis_jobs (created_at desc);
create index if not exists ix_video_jobs_status  on public.video_analysis_jobs (status);

-- ---------------------------------------------------------------------
-- detections  (one row per detection EVENT - never one row per frame)
-- ---------------------------------------------------------------------
create table if not exists public.detections (
    id                bigint generated by default as identity primary key,
    source            text        not null default 'Live Camera',  -- 'Live Camera' | 'Video Analysis'
    camera_id         bigint      references public.cameras (id) on delete set null,
    camera_name       text,
    video_analysis_job_id bigint  references public.video_analysis_jobs (id) on delete set null,
    location          text,

    object_name       text        not null,                    -- e.g. 'person'
    category          text        not null,                    -- Human | Animals | Vehicles | Others
    severity          text        not null default 'normal',   -- critical | warning | info | normal

    confidence        double precision not null default 0,      -- max confidence seen during the event
    avg_confidence    double precision not null default 0,
    frame_count       integer     not null default 1,           -- inference frames that contributed

    start_time        timestamptz not null default now(),
    end_time          timestamptz not null default now(),
    duration_seconds  double precision not null default 0,

    -- Object path inside the Supabase Storage 'snapshots' bucket.
    -- Only metadata/URLs live in Postgres, never the image bytes.
    snapshot_path     text,

    -- Latest bounding box of the event as [x1, y1, x2, y2] in pixels.
    bounding_box      jsonb,
    metadata          jsonb,

    client_event_id   uuid unique,      -- idempotency key: offline outbox replay can never duplicate a row
    created_at        timestamptz not null default now()
);

create index if not exists ix_detections_created   on public.detections (created_at desc);
create index if not exists ix_detections_object    on public.detections (object_name);
create index if not exists ix_detections_category  on public.detections (category);
create index if not exists ix_detections_severity  on public.detections (severity);
create index if not exists ix_detections_source    on public.detections (source);
create index if not exists ix_detections_camera_id on public.detections (camera_id);
create index if not exists ix_detections_camera_created  on public.detections (camera_id, created_at desc);
create index if not exists ix_detections_category_created on public.detections (category, created_at desc);

-- ---------------------------------------------------------------------
-- alerts
-- ---------------------------------------------------------------------
create table if not exists public.alerts (
    id            bigint generated by default as identity primary key,
    detection_id  bigint references public.detections (id) on delete set null,
    camera_id     bigint references public.cameras (id) on delete set null,
    camera_name   text,

    category      text,
    severity      text        not null default 'normal',
    alert_type    text,                                   -- 'intrusion' | 'animal_activity' | 'vehicle_activity' | 'object_detected'
    title         text        not null,                   -- preserved: human-readable title shown in the UI
    message       text        not null,

    acknowledged  boolean     not null default false,
    resolved      boolean     not null default false,

    created_at    timestamptz not null default now(),
    resolved_at   timestamptz,

    -- Always consistent with acknowledged/resolved - no dual writes to keep in sync.
    status text generated always as (
        case
            when resolved     then 'resolved'
            when acknowledged then 'acknowledged'
            else 'open'
        end
    ) stored,

    client_alert_id uuid unique     -- idempotency key for offline outbox replay
);

create index if not exists ix_alerts_created  on public.alerts (created_at desc);
create index if not exists ix_alerts_camera   on public.alerts (camera_id);
create index if not exists ix_alerts_severity on public.alerts (severity);
create index if not exists ix_alerts_resolved_created on public.alerts (resolved, created_at desc);

-- ---------------------------------------------------------------------
-- settings  (single row, id = 1 - identical to the original app)
-- ---------------------------------------------------------------------
create table if not exists public.settings (
    id                        integer primary key default 1,

    -- Detection
    confidence_threshold      double precision not null default 0.25,
    iou_threshold             double precision not null default 0.45,
    inference_interval_ms     integer not null default 400,   -- configurable inference FPS
    frame_skip                integer not null default 2,      -- configurable frame processing
    event_cooldown_seconds    integer not null default 8,

    -- Alerts / sound
    alerts_enabled            boolean not null default true,
    sound_enabled             boolean not null default true,
    alert_on_human            boolean not null default true,
    alert_on_animal           boolean not null default true,
    alert_on_vehicle          boolean not null default false,

    -- Storage
    snapshot_on_event         boolean not null default true,
    max_snapshot_age_days     integer not null default 30,

    -- Cloud sync / resource control
    sync_enabled              boolean not null default true,   -- master switch for AI-server -> Supabase sync
    upload_snapshots_to_cloud boolean not null default true,   -- keep false for 100% local, zero cloud storage

    -- Model
    model_path                text,
    stream_max_width          integer,                          -- optional downscale before inference

    updated_at timestamptz not null default now(),

    constraint settings_single_row check (id = 1)
);

insert into public.settings (id) values (1) on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- camera_status_history
-- Optional rolling log of camera online/offline transitions, useful for
-- diagnosing flaky network cameras after the fact. Small by design.
-- ---------------------------------------------------------------------
create table if not exists public.camera_status_history (
    id         bigint generated by default as identity primary key,
    camera_id  bigint references public.cameras (id) on delete cascade,
    status     text not null,
    fps        double precision,
    message    text,
    created_at timestamptz not null default now()
);

create index if not exists ix_camera_status_history_camera
    on public.camera_status_history (camera_id, created_at desc);

-- ---------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_cameras_updated_at on public.cameras;
create trigger trg_cameras_updated_at
    before update on public.cameras
    for each row execute function public.set_updated_at();

drop trigger if exists trg_camera_secrets_updated_at on public.camera_secrets;
create trigger trg_camera_secrets_updated_at
    before update on public.camera_secrets
    for each row execute function public.set_updated_at();

drop trigger if exists trg_settings_updated_at on public.settings;
create trigger trg_settings_updated_at
    before update on public.settings
    for each row execute function public.set_updated_at();
